### ISSUE TITLE
Todo for v1.0

### ISSUE THREAD

**Issue by jogibear9988** [iobroker-community-adapters/ioBroker.webui#137]
- [x] style editor (per screen, global)
- [x] how to store bindings, not how as it's done atm. converters should be possible, and more... maybe also js converters 
- [x] implement binding converters
- [x] simple script language & editor for events
- [x] javascript for events
- [x] dynamic dialog for editing of bindings
- [x] dragdrop objects to elements should create bindings
- [x] relative bindings path for display-screens
- [ ] Implement a registry for custom controls, normaly webcomponents (bspw: https://developer.visa.com/pages/chart-components/bar-chart, https://github.com/christianliebel/paint, https://wiredjs.com/,

**Comment by jogibear9988** [comment]
Create a few component Libaries, use some usabel components:

https://github.com/swina/rockiot-ui
https://dariancabot.com/2010/11/01/jgauge-a-100-javascript-dial-gauge/
https://www.cssscript.com/tag/gauge/

**Comment by jogibear9988** [comment]
[] remove imports rewriteing, use importmap polyfill and import shim

**Comment by jogibear9988** [comment]
More gauges:

https://github.com/boonzaai/doublegauge
https://github.com/Mikhus/canvas-gauges
https://github.com/swina/rockiot-gauge
https://nivo.rocks/
